-- 예약 목록 조회
SELECT TO_CHAR(PAYMENT_DT, 'YYYY-MM-DD') PAYMENT_DT, MEMBER_NM, ROOM_NO, 
       TO_CHAR(CHECK_IN, 'YYYY-MM-DD') CHECK_IN,
       TO_CHAR(CHECK_OUT, 'YYYY-MM-DD') CHECK_OUT
FROM RESERVATION_CHECK
JOIN RESERVATION_REQ R USING(REQUEST_NO)
JOIN PAYMENT USING(PAYMENT_NO)
JOIN MEMBER M ON(R.MEMBER_NO = M.MEMBER_NO)
WHERE RESERVATION_FL = 'Y';


-- 검색 목록 조회
SELECT * FROM(
    SELECT ROWNUM, A.* FROM(
        SELECT 
    ) A
)

-- 예약+결제 정보 조회


SELECT OPTION_TYPE, OPTION_COUNT, REQUEST_NO
FROM RESERVATION_CHECK
JOIN OPTION_ORDER O USING(REQUEST_NO)
JOIN OPTION_TB P ON(O.OPTION_CD=P.OPTION_CD);